[tool.black]
line-length = 100
target-version = ["py311"]
extend-exclude = "^migrations/versions/"

[tool.isort]
profile = "black"
line_length = 100
filter_files = true
skip_gitignore = true

[tool.ruff]
line-length = 100
target-version = "py311"
extend-exclude = ["migrations/versions/"]

[tool.ruff.lint]
select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "I",  # isort import order
  "UP", # pyupgrade
]
ignore = [
  "E501",  # let black handle line length
]

[tool.ruff.lint.per-file-ignores]
"migrations/env.py" = ["E402"]
"services/api/alembic/env.py" = ["E402"]
"services/api/app/main.py" = ["E402"]
"services/api/tests/test_scoring.py" = ["E402"]
